# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deletePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeleteWindow(object):
    def setupUi(self, DeleteWindow):
        DeleteWindow.setObjectName("DeleteWindow")
        DeleteWindow.resize(777, 580)
        self.centralwidget = QtWidgets.QWidget(DeleteWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(180, 500, 241, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 500, 131, 31))
        self.label.setStyleSheet("font: 26pt \".AppleSystemUIFont\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 460, 391, 31))
        self.label_2.setStyleSheet("font: 18pt \".AppleSystemUIFont\";")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(470, 450, 201, 51))
        self.pushButton.setStyleSheet("font: 20pt \".AppleSystemUIFont\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(470, 500, 201, 51))
        self.pushButton_2.setStyleSheet("font: 20pt \".AppleSystemUIFont\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 11, 741, 421))
        self.tableWidget.setRowCount(100)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setObjectName("tableWidget")
        DeleteWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(DeleteWindow)
        self.statusbar.setObjectName("statusbar")
        DeleteWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DeleteWindow)
        QtCore.QMetaObject.connectSlotsByName(DeleteWindow)

    def retranslateUi(self, DeleteWindow):
        _translate = QtCore.QCoreApplication.translate
        DeleteWindow.setWindowTitle(_translate("DeleteWindow", "MainWindow"))
        self.label.setText(_translate("DeleteWindow", "TCKN : "))
        self.label_2.setText(_translate("DeleteWindow", "Silmek İstediğiniz Hastanın TCKN\'sini giriniz."))
        self.pushButton.setText(_translate("DeleteWindow", "Kaydı Sil"))
        self.pushButton_2.setText(_translate("DeleteWindow", "Ana Menüye Dön"))
