# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'duzenlePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DuzenleWindow(object):
    def setupUi(self, DuzenleWindow):
        DuzenleWindow.setObjectName("DuzenleWindow")
        DuzenleWindow.resize(816, 652)
        self.centralwidget = QtWidgets.QWidget(DuzenleWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 331, 41))
        self.label.setStyleSheet("font: 32pt \".AppleSystemUIFont\";")
        self.label.setObjectName("label")
        self.tableDuzenle = QtWidgets.QTableWidget(self.centralwidget)
        self.tableDuzenle.setGeometry(QtCore.QRect(50, 70, 651, 391))
        self.tableDuzenle.setRowCount(100)
        self.tableDuzenle.setColumnCount(6)
        self.tableDuzenle.setObjectName("tableDuzenle")
        self.lineDuzenle = QtWidgets.QLineEdit(self.centralwidget)
        self.lineDuzenle.setGeometry(QtCore.QRect(160, 510, 291, 31))
        self.lineDuzenle.setObjectName("lineDuzenle")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 470, 491, 31))
        self.label_2.setStyleSheet("font: 20pt \".AppleSystemUIFont\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 510, 121, 31))
        self.label_3.setStyleSheet("font: 24pt \".AppleSystemUIFont\";")
        self.label_3.setObjectName("label_3")
        self.btnDuzenle = QtWidgets.QPushButton(self.centralwidget)
        self.btnDuzenle.setGeometry(QtCore.QRect(560, 490, 181, 51))
        self.btnDuzenle.setStyleSheet("font: 22pt \".AppleSystemUIFont\";")
        self.btnDuzenle.setObjectName("btnDuzenle")
        self.btnAnaSayfa = QtWidgets.QPushButton(self.centralwidget)
        self.btnAnaSayfa.setGeometry(QtCore.QRect(560, 540, 181, 51))
        self.btnAnaSayfa.setStyleSheet("font: 20pt \".AppleSystemUIFont\";")
        self.btnAnaSayfa.setObjectName("btnAnaSayfa")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 550, 121, 31))
        self.label_4.setStyleSheet("font: 24pt \".AppleSystemUIFont\";")
        self.label_4.setObjectName("label_4")
        self.lineDuzenle_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineDuzenle_2.setGeometry(QtCore.QRect(160, 550, 291, 31))
        self.lineDuzenle_2.setObjectName("lineDuzenle_2")
        DuzenleWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DuzenleWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 816, 24))
        self.menubar.setObjectName("menubar")
        DuzenleWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DuzenleWindow)
        self.statusbar.setObjectName("statusbar")
        DuzenleWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DuzenleWindow)
        QtCore.QMetaObject.connectSlotsByName(DuzenleWindow)

    def retranslateUi(self, DuzenleWindow):
        _translate = QtCore.QCoreApplication.translate
        DuzenleWindow.setWindowTitle(_translate("DuzenleWindow", "MainWindow"))
        self.label.setText(_translate("DuzenleWindow", "Hasta Kaydı Düzenleme"))
        self.label_2.setText(_translate("DuzenleWindow", "Düzenlemek istediğiniz hasta kaydının TCKN\'sini giriniz."))
        self.label_3.setText(_translate("DuzenleWindow", "Eski Değer:"))
        self.btnDuzenle.setText(_translate("DuzenleWindow", "Düzenle"))
        self.btnAnaSayfa.setText(_translate("DuzenleWindow", "Ana Sayfaya Dön"))
        self.label_4.setText(_translate("DuzenleWindow", "Yeni Değer:"))
