# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'goruntuleSayfa.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WindowGoruntule(object):
    def setupUi(self, WindowGoruntule):
        WindowGoruntule.setObjectName("WindowGoruntule")
        WindowGoruntule.resize(695, 480)
        self.centralwidget = QtWidgets.QWidget(WindowGoruntule)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 341, 31))
        self.label.setStyleSheet("font: 30pt \".AppleSystemUIFont\";")
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 50, 651, 361))
        self.tableWidget.setRowCount(1000)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setObjectName("tableWidget")
        self.goruntuleAnaSayfa = QtWidgets.QPushButton(self.centralwidget)
        self.goruntuleAnaSayfa.setGeometry(QtCore.QRect(230, 420, 191, 32))
        self.goruntuleAnaSayfa.setStyleSheet("font: 18pt \".AppleSystemUIFont\";")
        self.goruntuleAnaSayfa.setObjectName("goruntuleAnaSayfa")
        WindowGoruntule.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(WindowGoruntule)
        self.statusbar.setObjectName("statusbar")
        WindowGoruntule.setStatusBar(self.statusbar)

        self.retranslateUi(WindowGoruntule)
        QtCore.QMetaObject.connectSlotsByName(WindowGoruntule)

    def retranslateUi(self, WindowGoruntule):
        _translate = QtCore.QCoreApplication.translate
        WindowGoruntule.setWindowTitle(_translate("WindowGoruntule", "MainWindow"))
        self.label.setText(_translate("WindowGoruntule", "Kayıt Görüntüleme Sistemi"))
        self.goruntuleAnaSayfa.setText(_translate("WindowGoruntule", "Ana Menüye Dön"))
