# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 491, 41))
        self.label.setObjectName("label")

        self.btn_Yeni = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Yeni.setGeometry(QtCore.QRect(20, 90, 191, 61))
        self.btn_Yeni.setStyleSheet("font: 24pt \".AppleSystemUIFont\";")
        self.btn_Yeni.setObjectName("btn_Yeni")

        self.btn_Duzenle = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Duzenle.setGeometry(QtCore.QRect(20, 210, 191, 61))
        self.btn_Duzenle.setStyleSheet("font: 24pt \".AppleSystemUIFont\";")
        self.btn_Duzenle.setObjectName("btn_Goruntule")

        self.btn_Goruntule = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Goruntule.setGeometry(QtCore.QRect(20, 150, 191, 61))
        self.btn_Goruntule.setStyleSheet("font: 24pt \".AppleSystemUIFont\";")
        self.btn_Goruntule.setObjectName("btn_Duzenle")

        self.btn_Sil = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Sil.setGeometry(QtCore.QRect(20, 270, 191, 61))
        self.btn_Sil.setStyleSheet("font: 24pt \".AppleSystemUIFont\";")
        self.btn_Sil.setObjectName("btn_Sil")

        self.btn_Cikis = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Cikis.setGeometry(QtCore.QRect(20, 330, 191, 61))
        self.btn_Cikis.setStyleSheet("font: 20pt \".AppleSystemUIFont\";")
        self.btn_Cikis.setObjectName("btn_Cikis")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt;\">Hasta Kayıt, Denetleme Sistemi</span></p></body></html>"))
        self.btn_Yeni.setText(_translate("MainWindow", "Yeni Kayıt"))
        self.btn_Duzenle.setText(_translate("MainWindow", "Kayıt Düzenle"))
        self.btn_Goruntule.setText(_translate("MainWindow", "Kayıt Görüntüle"))
        self.btn_Sil.setText(_translate("MainWindow", "Kayıt Sil"))
        self.btn_Cikis.setText(_translate("MainWindow", "Uygulamadan Çık"))


